
# Acceptable parameters are name, pageRef, page, url, title, weight.
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to

[[main]]
 name = "Root"
 pageRef = "/"
 weight = 1

[[main]]
 name = "About"
 pageRef = "/about"
 weight = 5

[[main]]
 name = "Services"
 pageRef = "/Services"
 weight = 10


[[main]]
 name = "Portfolio"
 pageRef = "/Portfolio"
 weight = 15

[[main]]
 name = "Blog"
 pageRef = "/posts"
 weight = 20

 [[main]]
 name = "Case Study"
 pageRef = "/case-study"
 weight = 25

#[[main]]
# name = "Cert"
# pageRef= "/Cert"
# weight = 30

[[main]]
 name = "Contact"
 pageRef = "/Contact"
 weight = 35

#[[main]]
#  name = "example sub-menu 2"
#  parent = "Parent"
#  pageRef = "posts"
#  weight = 20

#[[subnavigation]]
#  name = "An interesting topic"
#  pageRef = "tags/interesting-topic"
#  weight = 10

#[[subnavigation]]
#  name = "My Awesome Category"
#  pre = "github"
#  pageRef = "categories/awesome"
#  weight = 20

#[[main]]
# name = "Categories"
# pageRef = "categories"
# weight = 50

#[[main]]
#  name = "Tags"
#  pageRef = "tags"
#  weight = 30


# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.


[[footer]]
  name = "Tags"
  pageRef = "tags"
  weight = 10

[[footer]]
  name = "Categories"
  pageRef = "categories"
  weight = 20
